  name: capfiscal_app
  description: "A new Flutter project."
  publish_to: 'none'

  version: 1.0.0+1

  environment:
    sdk: '>=3.3.3 <4.0.0'

  dependencies:
    flutter:
      sdk: flutter

    # --- FlutterFire (alineados y compatibles) ---
    firebase_core: ^3.15.1
    cloud_firestore: ^5.6.11
    firebase_storage: ^12.4.9
    firebase_auth: ^5.6.2   # <-- actualizado para resolver conflicto
    firebase_app_check: ^0.3.2

    # --- Otros paquetes usados en la app ---
    path_provider: ^2.1.3
    open_filex: ^4.7.0
    video_player: ^2.7.0
    youtube_player_iframe: ^5.1.2
    url_launcher: ^6.3.0
    shared_preferences: ^2.5.3
    image_picker: ^1.1.2     # <-- opcionalmente actualizado
    connectivity_plus: ^6.1.0
    cloud_functions: ^5.1.3
    flutter_stripe: ^10.2.0

  dependency_overrides:
    firebase_core_platform_interface: 6.0.0

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^6.0.0
    flutter_launcher_icons: ^0.13.1
    flutter_native_splash: ^2.4.0
    fake_cloud_firestore: ^3.1.0
    firebase_auth_mocks: ^0.14.0
    firebase_storage_mocks: 0.7.0

  flutter:
    uses-material-design: true

    assets:
      - assets/branding/splash/
      - assets/branding/icons/
      - assets/app_icon/icon.png
      - assets/capfiscal_logo.png   # (Coloca 2.0x/ y 3.0x en carpetas, no es necesario listarlas)

  flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/app_icon/icon.png"

  flutter_native_splash:
    color: "#0A0A0B"        # CapColors.bgTop
    color_dark: "#0A0A0B"
    image: assets/branding/splash/splash.png
    image_dark: assets/branding/splash/splash.png

    android_12:
      color: "#0A0A0B"
      color_dark: "#0A0A0B"
      image: assets/branding/splash/splash_android12.png
      image_dark: assets/branding/splash/splash_android12.png
      icon_background_color: "#0A0A0B"
      icon_background_color_dark: "#0A0A0B"